2016-11-13T20:23:56+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.5.0 (/home/wtobey/liars_poker/venv/bin/python 2.7.9) starting up.
2016-11-13T20:23:56+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-11-13T20:23:56+0000 [-] MultiEchoFactory starting on 45807
2016-11-13T20:23:56+0000 [twisted.plugins.LiarsBackend.MultiEchoFactory#info] Starting factory <twisted.plugins.LiarsBackend.MultiEchoFactory instance at 0x7fc564348f80>
2016-11-13T20:23:57+0000 [stdout#info] Build Protocol
2016-11-13T20:23:57+0000 [stdout#info] New Protocol
2016-11-13T20:23:57+0000 [stdout#info] New connection
2016-11-13T20:23:57+0000 [stdout#info] Data Recieved 2::3::170
2016-11-13T20:23:57+0000 [stdout#info] ID:  Handle Data: Type: 2Data: 170
2016-11-13T20:23:57+0000 [stdout#info] Player ID'D As: 170
2016-11-13T20:23:57+0000 [stdout#info] SENDING STRING: 00060007ID
2016-11-13T20:23:57+0000 [stdout#info] New iD to send 170
2016-11-13T20:23:57+0000 [stdout#info] Data Recieved 1::74::170+Will Tobey+will|173+Xander  Carlson +xcarldawg2012|170+Will Tobey+will0::73::<9d14932f 6bc125cd cbbeba13 db327eb0 ea9de2eb 0a0c3e09 fdd29810 ef2ad8de>
2016-11-13T20:23:57+0000 [stdout#info] ID: 170 Handle Data: Type: 1Data: 170+Will Tobey+will|173+Xander  Carlson +xcarldawg2012|170+Will Tobey+will
2016-11-13T20:23:57+0000 [stdout#info] Player ID List recieved
2016-11-13T20:23:57+0000 [stdout#info] New Player List170+Will Tobey+will|173+Xander  Carlson +xcarldawg2012|170+Will Tobey+will
2016-11-13T20:23:57+0000 [stdout#info] ID: 170 Handle Data: Type: 0Data: <9d14932f 6bc125cd cbbeba13 db327eb0 ea9de2eb 0a0c3e09 fdd29810 ef2ad8de>
2016-11-13T20:23:57+0000 [stdout#info] Data Dump
2016-11-13T20:23:57+0000 [stdout#info] ruby /home/wtobey/liars_poker/pushNotifications.rb -p 45807 -j /home/wtobey/liars_poker/Storage/GAME_akgyfccxkdxiyutpmotcrjhlfx/players.json
2016-11-13T20:23:57+0000 [stdout#info] Unknown Data Type
2016-11-13T20:24:14+0000 [stdout#info] Drop Connection
2016-11-13T20:24:14+0000 [MultiEcho,0,128.220.159.83] Unhandled Error
	Traceback (most recent call last):
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 310, in runReactorWithLogging
	    reactor.run()
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
	    self.mainLoop()
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1207, in mainLoop
	    self.doIteration(t)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
	    selectable.readConnectionLost(f)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 272, in readConnectionLost
	    self.connectionLost(reason)
	  File "/home/wtobey/liars_poker/venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/wtobey/liars_poker/twisted/plugins/LiarsBackend.py", line 225, in connectionLost
	    self.factory.gameState.players.remove(self)
	exceptions.ValueError: list.remove(x): x not in list
	
